theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
true-color = true # Fixes Helix on WSL

[editor.cursor-shape]
insert = "bar"
select = "underline"

[file-picker]
hidden = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
